//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailReview
    {
        public int ID { get; set; }
        public string ItemID { get; set; }
        public string ReviewBy { get; set; }
        public int ReviewRating { get; set; }
        public string ReviewComments { get; set; }
        public string ReviewTitle { get; set; }
        public int Display { get; set; }
    }
}
